### PR TITLE
Add contributing guide

### PR DESCRIPTION
**Pull request by JonasWanke**
### Checklist

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Review by MarcelGarus — APPROVED** [review]

**Review by skyz1 — APPROVED** [review]

**Review by ctiedt — APPROVED** [review]

**Comment by MarcelGarus** [comment]
Can this be merged?

**Comment by JonasWanke** [comment]
I'd like to wait for @fpottbaecker's review before merging this PR

**Comment by fpottbaecker** [comment]
Sorry for the delay, this kept ending up lower on my todo list

**Review by fpottbaecker — APPROVED** [review]
Looks good

**Pull request merged**
